version: '3.8'

services:
  postgres-database:
    image: postgres
    container_name: metric-postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
