-- public.account_user definition

-- Drop table

-- DROP TABLE public.account_user;

CREATE TABLE IF NOT EXISTS public.account_user (
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	username varchar(150) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	id uuid NOT NULL,
	email varchar(254) NOT NULL,
	CONSTRAINT account_user_email_key UNIQUE (email),
	CONSTRAINT account_user_pkey PRIMARY KEY (id),
	CONSTRAINT account_user_username_key UNIQUE (username)
);
CREATE INDEX account_user_email_0bd7c421_like ON public.account_user USING btree (email varchar_pattern_ops);
CREATE INDEX account_user_username_d393f583_like ON public.account_user USING btree (username varchar_pattern_ops);


-- public.auth_group definition

-- Drop table

-- DROP TABLE public.auth_group;

CREATE TABLE IF NOT EXISTS public.auth_group (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


-- public.category_base definition

-- Drop table

-- DROP TABLE public.category_base;

CREATE TABLE IF NOT EXISTS public.category_base (
	id uuid NOT NULL,
	"name" varchar(200) NOT NULL,
	slug varchar(200) NOT NULL,
	create_date date NOT NULL,
	update_date date NOT NULL,
	CONSTRAINT category_base_pkey PRIMARY KEY (id),
	CONSTRAINT category_base_slug_key UNIQUE (slug)
);
CREATE INDEX category_base_slug_5c7d7382_like ON public.category_base USING btree (slug varchar_pattern_ops);


-- public.django_content_type definition

-- Drop table

-- DROP TABLE public.django_content_type;

CREATE TABLE IF NOT EXISTS public.django_content_type (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model),
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);


-- public.django_migrations definition

-- Drop table

-- DROP TABLE public.django_migrations;

CREATE TABLE IF NOT EXISTS public.django_migrations (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	app varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	applied timestamptz NOT NULL,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);


-- public.django_session definition

-- Drop table

-- DROP TABLE public.django_session;

CREATE TABLE IF NOT EXISTS public.django_session (
	session_key varchar(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamptz NOT NULL,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


-- public.shop_platform definition

-- Drop table

-- DROP TABLE public.shop_platform;

CREATE TABLE IF NOT EXISTS public.shop_platform (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(20) NOT NULL,
	image varchar(100) NOT NULL,
	CONSTRAINT shop_platform_pkey PRIMARY KEY (id)
);


-- public.account_user_groups definition

-- Drop table

-- DROP TABLE public.account_user_groups;

CREATE TABLE IF NOT EXISTS public.account_user_groups (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	user_id uuid NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT account_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT account_user_groups_user_id_group_id_4d09af3e_uniq UNIQUE (user_id, group_id),
	CONSTRAINT account_user_groups_group_id_6c71f749_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT account_user_groups_user_id_14345e7b_fk_account_user_id FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX account_user_groups_group_id_6c71f749 ON public.account_user_groups USING btree (group_id);
CREATE INDEX account_user_groups_user_id_14345e7b ON public.account_user_groups USING btree (user_id);


-- public.auth_permission definition

-- Drop table

-- DROP TABLE public.auth_permission;

CREATE TABLE IF NOT EXISTS public.auth_permission (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NOT NULL,
	content_type_id int4 NOT NULL,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


-- public.category definition

-- Drop table

-- DROP TABLE public.category;

CREATE TABLE IF NOT EXISTS public.category (
	categorybase_ptr_id uuid NOT NULL,
	CONSTRAINT category_pkey PRIMARY KEY (categorybase_ptr_id),
	CONSTRAINT category_categorybase_ptr_id_d3eccad3_fk_category_base_id FOREIGN KEY (categorybase_ptr_id) REFERENCES public.category_base(id) DEFERRABLE INITIALLY DEFERRED
);


-- public.category_sub definition

-- Drop table

-- DROP TABLE public.category_sub;

CREATE TABLE IF NOT EXISTS public.category_sub (
	categorybase_ptr_id uuid NOT NULL,
	parent_id uuid NOT NULL,
	CONSTRAINT category_sub_pkey PRIMARY KEY (categorybase_ptr_id),
	CONSTRAINT category_sub_categorybase_ptr_id_457e8c1c_fk_category_base_id FOREIGN KEY (categorybase_ptr_id) REFERENCES public.category_base(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT category_sub_parent_id_60ff737d_fk_category_categorybase_ptr_id FOREIGN KEY (parent_id) REFERENCES public.category(categorybase_ptr_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX category_sub_parent_id_60ff737d ON public.category_sub USING btree (parent_id);


-- public.django_admin_log definition

-- Drop table

-- DROP TABLE public.django_admin_log;

CREATE TABLE IF NOT EXISTS public.django_admin_log (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	action_time timestamptz NOT NULL,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag int2 NOT NULL,
	change_message text NOT NULL,
	content_type_id int4 NULL,
	user_id uuid NOT NULL,
	CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)),
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
	CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT django_admin_log_user_id_c564eba6_fk_account_user_id FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


-- public.product definition

-- Drop table

-- DROP TABLE public.product;

CREATE TABLE IF NOT EXISTS public.product (
	id uuid NOT NULL,
	"name" varchar(200) NOT NULL,
	slug varchar(200) NOT NULL,
	create_date date NOT NULL,
	update_date date NOT NULL,
	description text NULL,
	image varchar(100) NOT NULL,
	price int4 NULL,
	category_id uuid NOT NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id),
	CONSTRAINT product_slug_key UNIQUE (slug),
	CONSTRAINT product_category_id_640030a0_fk_category_base_id FOREIGN KEY (category_id) REFERENCES public.category_base(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_category_id_640030a0 ON public.product USING btree (category_id);
CREATE INDEX product_slug_c4732ed0_like ON public.product USING btree (slug varchar_pattern_ops);


-- public.product_comment definition

-- Drop table

-- DROP TABLE public.product_comment;

CREATE TABLE IF NOT EXISTS public.product_comment (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	username varchar(30) NOT NULL,
	"content" text NOT NULL,
	create_date date NOT NULL,
	update_date date NOT NULL,
	product_id uuid NOT NULL,
	CONSTRAINT product_productcomments_pkey PRIMARY KEY (id),
	CONSTRAINT product_productcomments_product_id_2b8d1db5_fk_product_id FOREIGN KEY (product_id) REFERENCES public.product(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_productcomments_product_id_2b8d1db5 ON public.product_comment USING btree (product_id);


-- public.product_image definition

-- Drop table

-- DROP TABLE public.product_image;

CREATE TABLE IF NOT EXISTS public.product_image (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	image varchar(100) NOT NULL,
	product_id uuid NOT NULL,
	CONSTRAINT product_image_pkey PRIMARY KEY (id),
	CONSTRAINT product_image_product_id_8b9355c5_fk_product_id FOREIGN KEY (product_id) REFERENCES public.product(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_image_product_id_8b9355c5 ON public.product_image USING btree (product_id);


-- public.product_option definition

-- Drop table

-- DROP TABLE public.product_option;

CREATE TABLE IF NOT EXISTS public.product_option (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar NULL,
	price int4 NULL,
	product_id uuid NOT NULL,
	platform_id int8 NULL,
	sale_count int4 NOT NULL,
	link varchar NOT NULL,
	CONSTRAINT product_option_pkey PRIMARY KEY (id),
	CONSTRAINT product_option_platform_id_5ab2732b_fk_shop_platform_id FOREIGN KEY (platform_id) REFERENCES public.shop_platform(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT product_option_product_id_d757031a_fk_product_id FOREIGN KEY (product_id) REFERENCES public.product(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_option_platform_id_5ab2732b ON public.product_option USING btree (platform_id);
CREATE INDEX product_option_product_id_d757031a ON public.product_option USING btree (product_id);


-- public.account_user_user_permissions definition

-- Drop table

-- DROP TABLE public.account_user_user_permissions;

CREATE TABLE IF NOT EXISTS public.account_user_user_permissions (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	user_id uuid NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT account_user_user_permis_user_id_permission_id_48bdd28b_uniq UNIQUE (user_id, permission_id),
	CONSTRAINT account_user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT account_user_user_pe_permission_id_66c44191_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT account_user_user_pe_user_id_cc42d270_fk_account_u FOREIGN KEY (user_id) REFERENCES public.account_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX account_user_user_permissions_permission_id_66c44191 ON public.account_user_user_permissions USING btree (permission_id);
CREATE INDEX account_user_user_permissions_user_id_cc42d270 ON public.account_user_user_permissions USING btree (user_id);


-- public.auth_group_permissions definition

-- Drop table

-- DROP TABLE public.auth_group_permissions;

CREATE TABLE IF NOT EXISTS public.auth_group_permissions (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	group_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);